#!/usr/bin/env node
/**
 * ETH THROUGH THE ETHEREUM GAP — writes src/data/ethGap.json.
 *
 * The legacy VY/WETH pool (whose reserve was ETH alone) last traded 20 Dec 2025; the current
 * VY/USDC pool first traded 13 Apr 2026. Nothing traded in between, so the Since Genesis chart
 * bridges those 115 days with a path shaped by ETH (see `bridgeTrades` in priceHistory.ts). This
 * file is that shape: Chainlink's ETH/USD at the legacy pool's last trade, every ~6 hours after
 * it, and at the current pool's first trade.
 *
 * One `eth_call` per sample: Multicall3 reads the feed AND the block's own timestamp together.
 *
 *   node scripts/build-eth-gap.mjs [--rpc <url>] [--out <path>]
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createPublicClient, http, parseAbi } from 'viem';
import { mainnet } from 'viem/chains';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const STRIDE = 1_800; // ~6 hours of Ethereum blocks
const CONCURRENCY = 12;
const ETH_USD = '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419';

const FEED_ABI = parseAbi([
  'function description() view returns (string)',
  'function decimals() view returns (uint8)',
  'function latestRoundData() view returns (uint80, int256, uint256, uint256, uint80)',
]);
const MULTICALL_ABI = parseAbi(['function getCurrentBlockTimestamp() view returns (uint256)']);

const argv = process.argv.slice(2);
const arg = (n, d) => { const i = argv.indexOf(n); return i >= 0 && argv[i + 1] ? argv[i + 1] : d; };
const RPC = arg('--rpc', 'https://api.valinity.io/rpc-proxy');
const OUT = resolve(ROOT, arg('--out', 'src/data/ethGap.json'));

const client = createPublicClient({ chain: mainnet, transport: http(RPC, { timeout: 60_000 }) });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function mapLimit(items, limit, fn) {
  const out = new Array(items.length);
  let next = 0;
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (;;) { const i = next++; if (i >= items.length) return; out[i] = await fn(items[i], i); }
  }));
  return out;
}

// ── The two edges of the gap ────────────────────────────────────────────────
const vy = JSON.parse(readFileSync(resolve(ROOT, 'src/data/vyHistory.json'), 'utf8'));
const legacy = vy.trades.filter((t) => t.era === 'vy-legacy');
const lastLegacy = legacy[legacy.length - 1];
const firstCurrent = vy.trades.find((t) => t.era === 'vy-current');
if (!lastLegacy || !firstCurrent) throw new Error('vyHistory.json needs both vy-legacy and vy-current trades');

const description = await client.readContract({ address: ETH_USD, abi: FEED_ABI, functionName: 'description' });
if (description !== 'ETH / USD') throw new Error(`${ETH_USD} describes itself as "${description}", expected "ETH / USD"`);
const decimals = await client.readContract({ address: ETH_USD, abi: FEED_ABI, functionName: 'decimals' });

// ── Sample ──────────────────────────────────────────────────────────────────
const blocks = [];
for (let b = lastLegacy.block; b < firstCurrent.block; b += STRIDE) blocks.push(b);
blocks.push(firstCurrent.block);
console.log(`sampling ETH / USD at ${blocks.length} blocks (${lastLegacy.block} → ${firstCurrent.block}) ...`);

async function sampleAt(block) {
  for (let i = 0; i < 6; i++) {
    try {
      const [ts, round] = await client.multicall({
        blockNumber: BigInt(block),
        allowFailure: false,
        contracts: [
          { address: mainnet.contracts.multicall3.address, abi: MULTICALL_ABI, functionName: 'getCurrentBlockTimestamp' },
          { address: ETH_USD, abi: FEED_ABI, functionName: 'latestRoundData' },
        ],
      });
      return { block, ts: Number(ts), eth: Number(round[1]) / 10 ** decimals };
    } catch { await sleep(400 * 2 ** i); }
  }
  return null;
}

const samples = await mapLimit(blocks, CONCURRENCY, sampleAt);
const missing = samples.filter((s) => !s || !(s.eth > 0)).length;
if (missing) throw new Error(`${missing} of ${blocks.length} samples failed — refusing to write a path with holes`);
if (samples[0].ts !== lastLegacy.ts || samples[samples.length - 1].ts !== firstCurrent.ts) {
  throw new Error('edge samples do not land on the edge trades');
}

writeFileSync(OUT, JSON.stringify({
  _comment:
    'GENERATED by scripts/build-eth-gap.mjs — do not edit by hand. Chainlink ETH/USD from the ' +
    'legacy VY pool\'s last trade to the current pool\'s first, every ~6h: the shape the Since ' +
    'Genesis chart gives the 115 days no pool traded.',
  chain: 'ethereum', chainId: 1, feed: ETH_USD,
  samples,
}, null, 1) + '\n');
const e0 = samples[0].eth;
const e1 = samples[samples.length - 1].eth;
console.log(`wrote ${samples.length} samples → ${OUT}  (ETH $${e0.toFixed(0)} → $${e1.toFixed(0)}, ${((e1 / e0 - 1) * 100).toFixed(1)}%)`);
